# Generated by Django 4.2.2 on 2023-06-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_feedbackk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbackk',
            new_name='Feedback',
        ),
    ]
