# Generated by Django 4.2.2 on 2023-06-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
