# Generated by Django 4.2.1 on 2023-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_delete_orders_delete_price_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
